apiVersion: v1
kind: Pod
metadata:
  name: kubia-on-gpu
  labels:
    has_gpu: yes_has_gpu
spec:
  nodeSelector:
    gpu: "true"
  containers:
  - image: itsmetraw/kubia
    name: kubia-gpu
    ports:
    - containerPort: 8080
      protocol: TCP
